//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_XLII_Bojana_Backo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public string NameSurname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> CardID { get; set; }
        public string JMBG { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Sector { get; set; }
        public string Location { get; set; }
        public string Manager { get; set; }
    }
}
